apiVersion: apps/v1
kind: Deployment
metadata:
  name: votenirvan-apigateway-deployment
  labels:
    app: apigateway
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
      type: backend
  template:
    metadata:
      labels:
        app: apigateway
        type: backend
    spec:
      containers:
      - name: votenirvan-apigateway
        image: dsarva/apigateway
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 4444
      name: http
      restartPolicy: Always
  restartPolicy: Always
