apiVersion: apps/v1
kind: Deployment
metadata:
  name: votenirvan-result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
        type: backend
    spec:
      containers:
      - name: votenirvan-result
        image: dsarva/result
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 4004
          name: http
