apiVersion: apps/v1
kind: Deployment
metadata:
  name: votenirvan-twilio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twilio
      type: backend
  template:
    metadata:
      labels:
        app: twilio
        type: backend
    spec:
      containers:
      - name: votenirvan-result
        image: dsarva/twilio
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 4006
          name: http
