apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Release.Name  }}-vn-candidate
  labels:
    app: candidate
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candidate
      type: backend
  template:
    metadata:
      labels:
        app: candidate
        type: backend
    spec:
      containers:
      - name: votenirvan-candidate
        image: {{ .Values.image.repository }}/candidate
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 4001
          name: http
      restartPolicy: Always
