apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Release.Name  }}-vn-vote
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
      type: backend
  template:
    metadata:
      labels:
        app: vote
        type: backend
    spec:
      containers:
      - name: votenirvan-vote
        image: {{ .Values.image.repository }}/vote
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 4003
          name: http
